# No configuration required for GitLab CI/CD. It simply works.
image: node:20

pages:
  stage: deploy
  script:
    - npm install
    - npm run build # or `node build your-site.config.js`

  artifacts:
    paths:
      - public

  only:
    - main
