# No configuration required for GitLab CI/CD. It simply works.
image: node:20

pages:
  stage: deploy
  script:
    - npm install
    - npm run build

  artifacts:
    paths:
      - public

  only:
    - main
